name: Update RSS Feed

on:
  schedule:
    # Runs at 12 AM UTC every day
    - cron: '0 0 * * *'

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install ffmpeg
      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Or specify the version you need

      # Install dependencies from Gemfile
      - name: Install dependencies
        run: |
          bundle install

      # Set up Google Service Account
      - name: Set up Google Service Account
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service_account.json

      # Run the Ruby script to update RSS feed
      - name: Run the script
        run: |
          ruby update_rss_feed.rb

      # Commit changes if the RSS feed gets updated
      - name: Commit changes
        run: |
          git config --local user.email "sunilkumar.gec56@gmail.com"
          git config --local user.name "GitHub Actions"
          git add rss.xml
          git commit -m "Updated RSS feed" || echo "No changes to commit"
          git push
