name: Update RSS Feed

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install ffmpeg
      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Or specify the version you need

      # Install dependencies from Gemfile
      - name: Install dependencies
        run: |
          bundle install

      # Set up Google Service Account
      - name: Set up Google Service Account
        run: | 
          echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT }} | base64 -d > service_account.json
          cat service_account.json

      # Run the Ruby script to update RSS feed
      - name: Run the script
        run: |
          bundle exec ruby update_rss_feed.rb

      # Commit changes if the RSS feed gets updated
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "sunilkumar.gec56@gmail.com"
          git config --local user.name "GitHub Actions"
          git add podcast_rss.xml
          git commit -m "Updated RSS feed" || echo "No changes to commit"
          git push
